### ISSUE TITLE
Séléction du match en 2 temps

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#11]
1) le match pré-selectionne les 2 prochains lutteurs et affiche juste leur nom, pays et couleur sur le scoreboard
2) l'opérateur clique sur un bouton "Match Ready" pour que les scores et le temps d'affichent

**Comment by FmodouX** [comment]
Sur la fenêtre de l'opérateur ou publique ?

**Comment by FmodouX** [comment]
@sguenat tu as un petit exemple de ce que tu veux en pré-load du match sur l'écran publique ?

**Comment by FmodouX** [comment]
Faire un refresh 'thread safe' à la fin de chaque match pour ifentifier si il y a un expectedStartTime

**Comment by FmodouX** [comment]
@sguenat 

dans l'ordre il y a :
- sélection du vainqueur ainsi que des points de classements.
- Affichage pendant XX secondes du pavé final sur l'écran publique avec le UI opérateur vide
- Bouton pour afficher le nouvel écran d'attente ou auto après XX secondes ?
- Une fois l'écran d'attente affiché sur l'écran publique, juste afficher un bouton sur le UI opérateur "Match ready".
Une fois cliqué sur ce bouton match ready, on bascule sur l'interface normal d'un nouveau match (UI opérateur et publique).

Je te laisse corriger ce que tu veux différent ou alors préciser les durée à la place des XX.

Merci

**Comment by FmodouX** [comment]
A tester dans la version 28 ! Il faut des matches ouverts ainsi que des match avec la clé expectedStartDate afin de tester le tout.

C'est possible d'activer le waiting screen manuellement depuis le menu.
