### ISSUE TITLE
BUG : A la fin d'un match, tenter de charger le prochain, si il n'y en a pas, relaoder depuis Arena et charger le suivant

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#12]

**Comment by FmodouX** [comment]
Une fois le match terminé, proposer de pré-loader le suivant, une fois fait afficher un résumé du prochain match sur l'écran publique puis une fois prêt charger le match normal. 2 étapes en + avec 2 boutons.

**Comment by sguenat** [comment]
Si plus de match disponible, afficher LogoFull

**Comment by sguenat** [comment]
Comme demandé dans ton mail voici le détail du sénario 

Le match se termine, séléction du vainqueur, attribution des points de classement...
La barre de progression (verte) s'affiche pour les quelques secondes d'attentes
Une pop-up s'affiche et propose de pré-loader le prochain match (pendant ce temps sur le scoreboard on est toujours entrain d'afficher la victoire précédente) ou de selectionner un autre match.
Une fois qu'on a cliqué sur "Pre-load the next match" le nom des lutteurs s'affichent en gros sur le scoreboard public, sans temps (voir exemple swisstiming). L'opérateur lui voit juste 2 boutons, un "Load the selected match" et un "select another match".
Une fois qu'il clique "Load the selected match" on se retrouve avec l'interface de scoreboard normale...

**Comment by sguenat** [comment]
![img_20181014_175648](https://user-images.githubusercontent.com/9988914/46922159-5b383d80-cfdb-11e8-80c9-4ce21577d1bb.jpg)

**Comment by sguenat** [comment]
Je sais que pas le passé j'avais fait un autre designe pour l'écran intermédiaire, mais finalement j'aimerais qu'il corresponde à l'image swisstiming ci-dessus. Merci

**Comment by FmodouX** [comment]
@sguenat c'est en ordre cette partie-là il me semble ?
