### ISSUE TITLE
Dans la pop up de config, renseigner également le tapis à cet endroit (1-2-3-4)

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#20]

**Comment by FmodouX** [comment]
Etant un paramètre avec redémarrage obligatoire du programme (pour cause des socket) je pense judicieux de les séparer... Je pense te rajouter en revanche dans la fenêtre de configuration une combo pour l'interface réseau à utiliser.

**Comment by FmodouX** [comment]
Patché dans 1.0.1.7. Le reboot est toujours nécessaire pour une question de port de communication...
