### ISSUE TITLE
Créer une interface différente pour le mat chairman (qui peut être changée dans le menu)

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#21]

**Comment by FmodouX** [comment]
@sguenat tu as une exemple de ce à quoi tu aimerais que ça ressemble ?

**Comment by sguenat** [comment]
![freestyle](https://user-images.githubusercontent.com/9988914/43260429-bdaca51e-90d9-11e8-90e0-a5d6873eda25.JPG)
![greco](https://user-images.githubusercontent.com/9988914/43260435-c445c1ee-90d9-11e8-881d-f95428dd9c58.JPG)

**Comment by FmodouX** [comment]
A effet mémoire dans la configuration du programme (setup)

**Comment by FmodouX** [comment]
@sguenat cette partie-là est en ordre il me semble ?
