### ISSUE TITLE
BUG : Le soft n'utilise pas toujours la bonne interface réseau pour envoyer les paquets UDP (plus d'info dans la desciption)

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#26]
1.	For some reason the app does not select the active NIC in all cases. Like I have VirtualBox installed on my computer where I run the scoreboard app and only the Host only VBox network card was used to send the UDP packets. It did not make sense if I changed the network card order in Windows (put the Host only adapter to the bottom of the list), the app still used that network interface card for binding. However if I disabled that network interface, the app started sending the packets on the Ethernet adapter.

**Comment by FmodouX** [comment]
Créer une liste avec les différents interfaces réseau pour pouvoir choisir le bon interface..

**Comment by FmodouX** [comment]
A tester mais normalement c'est codé.. je get TOUS les interfaces de Windows...

**Comment by FmodouX** [comment]
A noter que je te confirme bien que j'utlise le broadcast pour l'envoie des paquets.. donc le masque de sous-réseau doit être respecté sinon tu peux avoir des bugs bizzard..

Classe A => 255.0.0.0
Classe B => 255.255.0.0
Classe C => 255.255.255.0
