### ISSUE TITLE
BUG : clk01/2:59/stopEnd n'est pas envoyée à chaque fois

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#27]
The "clk01/2:59/stopEnd" message is not sent all the time. I just had the following message sequence:
UDPClient: Received data: clk10/2:57
UDPClient: Received data: clk10/2:58
UDPClient: Received data: clk10/2:59
UDPClient: Received data: brk1/29
UDPClient: Received data: brk1/28
UDPClient: Received data: brk1/27

**Comment by FmodouX** [comment]
J'ai corrigé le stopEnd qui devait suivre le 3:00 et non le 2:59. A tester dans la dernière build et en cas de soucis, sniffer la sortie du programme.
