### ISSUE TITLE
BUG : il arrive que avt0 ne soit pas suivi du message sc1/ 

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#29]
4.	I have seen one or perhaps two cases when avt0 was not followed with sc1/ message

**Comment by FmodouX** [comment]
@sguenat D'après le source un 'sc1' suit toujours un 'avt'. Faudrait sniffer la trame sortante pour être certain...

**Comment by sguenat** [comment]
C'est justement un gars qui essayait de developper une app pour lire ta trame qui m'a signalé le problème...

**Comment by FmodouX** [comment]
En udp c'est possible que le paquet soit envoyé mais qu'il ne soit pas reçu ou alors collé étant donné qu'il colle un autre paquet.. Je l'ai sniffé et tous paquets sortent.. si le problème se représente il faut sniffer la sortir du programme afin d'identifier si les paquets sont bien envoyés.
