### ISSUE TITLE
BUG : Dans les critères de victoires, la grande supériorité (VSU et VSU1) en GR c’est à 8 pts techniques de différence qu’il faut l’afficher. En freestyle c’est ok comme c’est maintenant (à 10 pts tech de différence)

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#3]

**Comment by FmodouX** [comment]
Trouver un moyen de passer un paramètre par Arena afin d'éviter de coder le soft timing selon un sport.

**Comment by sguenat** [comment]
ok - on va créer un paramettre - VSU qui contiendra un interger du nombre de point de différence necessaire pour activer ce type de victoire.

**Comment by FmodouX** [comment]
@sguenat maintenant que j'ai le paramètre c'est si l'écart des points entre A & B est supérieur (ou égal) à ce paramètre, je dois afficher les points techniques de grande supériorité ?

**Comment by FmodouX** [comment]
@sguenat à tester dans la version 1.0.1.7.

**Comment by FmodouX** [comment]
@ retester dans la v.14
