### ISSUE TITLE
Dialogue des bumper toutes les secondes pour le status des boutons..

### ISSUE THREAD

**Issue by FmodouX** [FmodouX/UWWtiming#39]

**Comment by FmodouX** [comment]
Tu veux ça dans la fenêtre main ou seulement dans la fenêtre des bumper ?

**Comment by sguenat** [comment]
on peut mettre ça en petit dans la fenêtre main, un petit rond vert à côté des boutons de challenges (et si pas de bumper pas de petit rond du tout (vu que la plupart du temps il n'y en aura pas)
