### ISSUE TITLE
BUG : Lorsqu'il y a une demande de challenge après la sélection du vainqueur, le challenge ne fonctionne plus par la suite (prochain match).

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#4]

**Comment by FmodouX** [comment]
Par un des bumper ?

**Comment by sguenat** [comment]
les 2 ne répondent plus, en gros il reste en mode "Y'a un challenge en attente à traiter" et du coup ignore les bumpers pour les matchs suivants également. à Contrôler aussi si ça arrive pendant la pause.

**Comment by FmodouX** [comment]
A tester dans la dernière build.
