### ISSUE TITLE
BUG : Selection du match en 2 temps

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#48]
Comme tu peux le voir sur cette video, la selection du prochain match ne fonctionne pas comme elle devrait.
https://www.youtube.com/watch?v=9_1NGq1WOCU&feature=youtu.be

**Comment by sguenat** [comment]
Egalement, au niveau du design, merci d'avoir ajouté le carré pour l'avantage mais mainenant il passe par dessus les cautions et les passivités, aussi les chiffres mordent un peu dedans, ce serait top de réduire un peu la police, la passer en gras et la centrer verticalement.

**Comment by FmodouX** [comment]
Zone corrigée, pastilles réduite, font changé de Lucida Console (font imposée au dév) à Arial

Pour le scénario, il faut m'expliquer exactement où ça coince et des matches ouverts pour pouvoir tester. Sinon je n'ai que les match vide pour tester et ça n'est pas comme en prod..
