### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by eveyrat** [FmodouX/UWWtiming#49]
@FmodouX 
Peux-tu stp mettre les valeurs par défaut suivantes à la première ouverture du soft :

Host : http://10.0.0.100:8080
Client ID : 2_37mtr5mww54w0ockgcosgkso88404ksk44w88kk4kosow80sk0
Client Secret : srspw76f4ggc80c40cgks80c8cwsw8kksgsokwk88owccs08s
API Key : 7U4YiGrWoFwp2VsHwzbQvZC2vWXp2e

Les champs ID et password ne sont utilisés que pour tes tests sur le staging.
Il y a beaucoup de gens qui nous contacte ne sachant pas quoi mettre.
A mon avis on peut soit virer ces 2 champs, soit trouver un endroit beaucoup plus discret.

**Comment by FmodouX** [comment]
Champ ID et password masqués.

Clés CID, CSecret et APIKEY changées.

Le bouton default reste obligatoire du fait de la détection si le scoreboard doit tourner en manuel et la sélection de l'interface réseau.
