### ISSUE TITLE
BUG : Trames UDP envoyée 2 fois à chaque fois

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#50]
![image 1](https://user-images.githubusercontent.com/9988914/47022748-8aae8d80-d134-11e8-8f47-f6a0d18a3e79.png)
Je sais pas si c'est normal mais youssef me dit que chaque trame UDP est envoyée 2 fois, qu'avec les dernières versions, avant ça faisait pas.

**Comment by FmodouX** [comment]
Pas constaté le bug. Peut-^'etre dis aucun interface n'est sélectionné ?
