### ISSUE TITLE
[UDP] WinnerMatch - wrong sequence

### ISSUE THREAD

**Issue by csabavirag** [FmodouX/UWWtiming#51]
In 1.0.9.33 I can see the following UDP flow:

1. Selecting the winner
wmh;Name (Country);
2. Confirming the winner
wmh;Name (Country);4-1VSU1;
wg1;0;wg2;0;
ct1;0;ct2;0;
wmh;Name (Country);

Is the last (wmh) packet necessary?

**Comment by FmodouX** [comment]
@csabavirag We have 2 different sequences for the wmh; 
The first one is for the TVG and must be quickly sent on the UDP for the live TV as soon as the winner is selected and the second one is with the classification points. 

But as I can see you received 2 times wmh; when confirming the winner and that should not be the case. I've just tested it in the last release 1.1.22.61 and I get the correct streams. wmh without classifications point when selecting the winner and wmh with classification points when confirming.

**Comment by csabavirag** [comment]
@FmodouX I downloaded the 1.1.22.61 version, but still can see this:
![image](https://user-images.githubusercontent.com/10976654/67095632-af5d9b00-f1b6-11e9-92ed-97b7d353c129.png)

**Comment by FmodouX** [comment]
@csabavirag Thanks for your feedback.

This is what I get in Wireshark from dev machine..

![winnerConfirmed](https://user-images.githubusercontent.com/25102845/67097516-8e974480-f1ba-11e9-9a12-fad2e04c6f25.png)

Are you sure you are not performing any request that could explain the problem ?

**Comment by csabavirag** [comment]
@FmodouX I apologize, I got confused with the message log order. You can see the time column (1st) on my screenshot, so you will see the 5th entry at the bottom was about when selecting the winner and the 1st-4th entries are about when confirming (timestamp is for several seconds later). 
So yes, I can confirm there is no empty wmh message anymore (although there are 2 similar packets after confirming the winner (1st & 4th). But those are similar, so not a problem for me.
Thank you for fixing it!

**Comment by FmodouX** [comment]
@csabavirag Thanks for your feedback ! No problem the most important is we fixed the bug ! Thanks for your issue ! Don't hesitate in case you see anything else :)
Best regards
