### ISSUE TITLE
Forfait ou Injury Match

### ISSUE THREAD

**Issue by bouaziz1991** [FmodouX/UWWtiming#52]
Si on a un match Injury ou Forfeit, le lutteur gagnant monte sur le tapis, on lève la main et sur le scoreboard on finit le match directement, ensuite le match suivant, le scoreboard affiche les nouveaux noms et pays mais n'envoie pas ses données en UDP.

**Comment by FmodouX** [comment]
@bouaziz1991 le problème est toujours dans la dernière version ? Pas mal de patch sur l'UDP ont été apporté depuis le 17 mars ;)

**Comment by bouaziz1991** [comment]
Done ;) tu peux fermer cette issue :D

**Comment by FmodouX** [comment]
Ok merci !
