### ISSUE TITLE
App launch requires "Run as Administrator"

### ISSUE THREAD

**Issue by csabavirag** [FmodouX/UWWtiming#59]
Simply clicking on the App icon, does not seem to happen anything. In the process list the app is shown up for a second then disappears.
If "Run as Administrator" is chosen then the app launches properly.

If that's a requirement to run as admin, please embed the necessary manifest tag ( `<requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>`) into the exe file.
That helps users with no experience to the UWWTiming app to run the app without looking for help.

**Comment by FmodouX** [comment]
Patched in the next release 1.1.23.62 (not available yet) ! Thanks !
