### ISSUE TITLE
App crashes if credentials are invalid

### ISSUE THREAD

**Issue by csabavirag** [FmodouX/UWWtiming#60]
To reproduce the issue:
1. close the app
1. update user.config and change any of the ClientID/ClientSecret/ApiKey values.
1. launch the app => it "crashes" silently.

It might happen that credentials are changed on server side, or on the client (by reason or accidentally).

reproducible in v1.1.22.61.

**Comment by FmodouX** [comment]
Patched in the next release 1.1.23.62 (not available yet) ! Thanks ! It now tells that configuration is not correct and prompt the connection window to correct the settings.
