### ISSUE TITLE
Countup-countdown

### ISSUE THREAD

**Issue by FmodouX** [FmodouX/UWWtiming#7]

**Comment by FmodouX** [comment]
Sitôt que la chaine complète (dartfish, etc..) est prête on peut laisser le choix.

**Comment by sguenat** [comment]
Alors dans l'ordre on va t'envoyer la data via Arena avec un nouveau champs dans le match, mais ce serait bien que par défaut le match demo soit avec un timer qui aille de 6:00 à 0:00. Dès que c'est fait je regarderais avec ton père pour qu'il modifie le GVI (dartfish) en fonction.

**Comment by FmodouX** [comment]
Fait dans V 1.0.1.5
