### ISSUE TITLE
Trame UPD Universelle

### ISSUE THREAD

**Issue by sguenat** [FmodouX/UWWtiming#9]

**Comment by FmodouX** [comment]
MAT
fightNumber
sport
age
clock
Countries
WRESTLERS
Scores
Warnings
cautions
activity
injury
avantage
winner
classificationPts

broadcasted on port 10'000 NCY

**Comment by FmodouX** [comment]
MAT/fightNumber/sport/age/clock/Countries/WRESTLERS/Scores/Warnings/cautions/activity/injury/avantage/winner/classificationPts broadcasted on port 33100
